pom.xml
=> Remove explicit version from dropwizard-migrations

.gitignore
Make the .gitignore like the other ones in kiwi repositories.
=> Ignore VSCode settings in git

src/main/java/org/kiwiproject/champagne/core/AuditRecord.java, src/main/java/org/kiwiproject/champagne/jdbi/AuditRecordDao.java, src/main/java/org/kiwiproject/champagne/jdbi/mappers/AuditRecordMapper.java, src/main/resources/migrations.xml, src/test/java/org/kiwiproject/champagne/jdbi/AuditRecordDaoTest.java, src/test/java/org/kiwiproject/champagne/jdbi/UserDaoTest.java
* Add tests for dao
* Fix variables and test method names in UserDaoTest
References #58
=> Add audit record model, db migration and daos

pom.xml
=> Clean out plugins that come from kiwi-parent

src/test/java/org/kiwiproject/champagne/dao/AuditRecordDaoTest.java, src/test/java/org/kiwiproject/champagne/dao/DeploymentEnvironmentDaoTest.java, src/test/java/org/kiwiproject/champagne/dao/ReleaseDaoTest.java, src/test/java/org/kiwiproject/champagne/dao/ReleaseStatusDaoTest.java, src/test/java/org/kiwiproject/champagne/dao/TaskDaoTest.java, src/test/java/org/kiwiproject/champagne/dao/TaskStatusDaoTest.java, src/test/java/org/kiwiproject/champagne/dao/TestDbObjects.java, src/test/java/org/kiwiproject/champagne/dao/UserDaoTest.java, src/test/java/org/kiwiproject/champagne/resource/AuthResourceTest.java, src/test/java/org/kiwiproject/champagne/util/TestObjects.java
=> Extract test model instance creation for dao tests

src/main/java/org/kiwiproject/champagne/dao/DeploymentEnvironmentDao.java, src/main/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResource.java, src/test/java/org/kiwiproject/champagne/dao/DeploymentEnvironmentDaoTest.java, src/test/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResourceTest.java
=> Add CRUD endpoints for DeploymentEnvironments

ui/.env, ui/.env.gitpod, ui/.env.prod, ui/.quasar/quasar-user-options.js, ui/quasar.config.js, ui/src/layouts/MainLayout.vue, ui/src/pages/DeploymentEnvironmentPage.vue, ui/src/pages/LoginPage.vue, ui/src/pages/UserPage.vue, ui/src/router/routes.js, ui/src/stores/deploymentEnvironment.js
* Add .env files to help with development between local laptop, production and gitpod
* Update User page to move add button to floating action
* Small style tweaks on Login page
Closes #90
=> Add Deployment environment page

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/resource/AuditRecordResource.java, service/src/test/java/org/kiwiproject/champagne/resource/AuditRecordResourceTest.java
=> Add endpoints to list audit records

ui/src/layouts/MainLayout.vue, ui/src/pages/AuditRecordsPage.vue, ui/src/router/routes.js
=> Add Audit viewing page

service/src/main/java/org/kiwiproject/champagne/model/Build.java, service/src/test/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResourceTest.java
=> Add model for Builds

service/src/main/java/org/kiwiproject/champagne/resource/ReleaseWithStatus.java, service/src/main/java/org/kiwiproject/champagne/resource/TaskResource.java, service/src/main/java/org/kiwiproject/champagne/resource/TaskWithStatus.java, service/src/test/java/org/kiwiproject/champagne/resource/TaskResourceTest.java, ui/package.json, ui/src/layouts/MainLayout.vue, ui/src/pages/ManualTaskPage.vue, ui/src/router/routes.js, ui/src/stores/deploymentEnvironment.js
* Small tweaks to endpoints to support UI
Closes #91
=> Add UI for Manual tasks

service/src/main/java/org/kiwiproject/champagne/App.java
=> Add the ability for configuration values to be set by env

service/src/test/java/org/kiwiproject/champagne/junit/jupiter/JwtExtension.java, service/src/test/java/org/kiwiproject/champagne/resource/AuditRecordResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/TaskResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/UserResourceTest.java
=> Add Junit extension to setup and tear down the jwt principal

service/src/main/java/org/kiwiproject/champagne/dao/BuildDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/BuildMapper.java, service/src/main/java/org/kiwiproject/champagne/model/Build.java, service/src/main/resources/migrations.xml, ui/src/layouts/MainLayout.vue, ui/src/pages/BuildsPage.vue, ui/src/router/routes.js
* Also add missing changelog field to builds
Closes #104
=> Add Build Page to UI

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/config/AppConfig.java, service/src/main/java/org/kiwiproject/champagne/dao/AuditRecordDao.java, service/src/main/java/org/kiwiproject/champagne/job/CleanOutAuditsJob.java, service/src/test/java/org/kiwiproject/champagne/AppTest.java, service/src/test/java/org/kiwiproject/champagne/dao/AuditRecordDaoTest.java, service/src/test/java/org/kiwiproject/champagne/job/CleanOutAuditsJobTest.java
Default is to run once a day and delete anything older than 30 days
Closes #106
=> Add an auto clean job for audit records

service/src/main/java/org/kiwiproject/champagne/model/Component.java, service/src/main/java/org/kiwiproject/champagne/model/Host.java
=> Add models for Host and Components

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/dao/BuildDao.java, service/src/main/java/org/kiwiproject/champagne/dao/DaoHelper.java, service/src/main/java/org/kiwiproject/champagne/dao/HostDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/HostMapper.java, service/src/main/java/org/kiwiproject/champagne/resource/HostConfigurationResource.java, service/src/main/resources/migrations.xml, service/src/test/java/org/kiwiproject/champagne/AppTest.java, service/src/test/java/org/kiwiproject/champagne/dao/DeploymentEnvironmentDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/HostDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/ReleaseStatusDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/TaskStatusDaoTest.java, service/src/test/java/org/kiwiproject/champagne/resource/BuildResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/HostConfigurationResourceTest.java, service/src/test/java/org/kiwiproject/champagne/util/TestObjects.java, ui/src/layouts/MainLayout.vue, ui/src/pages/HostConfigurationPage.vue, ui/src/pages/ManualTaskPage.vue, ui/src/router/routes.js, vetur.config.js
* DAO: Insert, list and delete of hosts
* Resource: Insert, list and delete hosts
* UI: Listing, create and delete of hosts
* Tests for new classes
* Clean out unused userId argument on test objects deployment environment creation
Closes #114
=> Add manual host management

service/src/main/java/org/kiwiproject/champagne/resource/TaskResource.java, service/src/test/java/org/kiwiproject/champagne/resource/TaskResourceTest.java, ui/src/pages/ManualTaskPage.vue, ui/src/stores/releaseStageStore.js
* Add GET endpoint
* Add unit test for endpoint
* Add pinia store for release stages
* Update page to use release stage store
Closes #99
=> Add endpoint to retrieve release stages

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/dao/ComponentDao.java, service/src/main/java/org/kiwiproject/champagne/dao/HostDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/ComponentMapper.java, service/src/main/java/org/kiwiproject/champagne/resource/HostConfigurationResource.java, service/src/test/java/org/kiwiproject/champagne/dao/ComponentDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/HostDaoTest.java, service/src/test/java/org/kiwiproject/champagne/resource/HostConfigurationResourceTest.java, service/src/test/java/org/kiwiproject/champagne/util/TestObjects.java, ui/src/pages/HostConfigurationPage.vue
=> Add dao, endpoints and UI for managing components

ui/src/layouts/MainLayout.vue
=> Make the left menu drawer work mo betta

service/src/main/java/org/kiwiproject/champagne/dao/UserDao.java, service/src/main/java/org/kiwiproject/champagne/model/User.java, service/src/main/java/org/kiwiproject/champagne/resource/UserResource.java, service/src/test/java/org/kiwiproject/champagne/resource/AuthResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/UserResourceTest.java
Also fix some other little user related issues
Closes #107
=> Add endpoint to update a user

ui/.quasar/app.js, ui/.quasar/client-entry.js, ui/src/pages/UserPage.vue, ui/src/stores/userStore.js, ui/test/vitest/__tests__/pages/UserPage.spec.js, ui/test/vitest/__tests__/stores/userStore.spec.js, ui/vitest.config.js
=> Add edit user UI

service/src/main/java/org/kiwiproject/champagne/dao/BuildDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/BuildMapper.java, service/src/main/java/org/kiwiproject/champagne/model/Build.java, service/src/main/java/org/kiwiproject/champagne/model/GitProvider.java, service/src/main/resources/migrations.xml, service/src/test/java/org/kiwiproject/champagne/dao/BuildDaoTest.java, service/src/test/java/org/kiwiproject/champagne/util/TestObjects.java, ui/package.json, ui/src/pages/BuildsPage.vue, ui/test/vitest/__tests__/pages/BuildsPage.spec.js, ui/yarn.lock
This will allow for link generation and appropriate displays
Closes #109
=> Add git provider to builds

ui/src/pages/BuildsPage.vue, ui/test/vitest/__tests__/pages/BuildsPage.spec.js
Will revisit once we decide how to visualize the change log
Closes #113
=> Fix security hotspot for formatting changelog

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/dao/ReleaseDao.java, service/src/main/java/org/kiwiproject/champagne/dao/TaskDao.java, service/src/main/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResource.java, service/src/main/java/org/kiwiproject/champagne/service/ManualTaskService.java, service/src/test/java/org/kiwiproject/champagne/dao/ReleaseDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/TaskDaoTest.java, service/src/test/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResourceTest.java, service/src/test/java/org/kiwiproject/champagne/service/ManualTaskServiceTest.java
=> Add new release and task status for existing ones when a new env is created

ui/src/layouts/MainLayout.vue, ui/src/pages/ErrorsPage.vue, ui/src/router/routes.js, ui/src/stores/errorStore.js, ui/test/vitest/__tests__/pages/ErrorsPage.spec.js, ui/test/vitest/__tests__/stores/errorStore.spec.js, ui/test/vitest/__tests__/stores/hostStore.spec.js
=> Add ui for application errors

service/src/main/java/org/kiwiproject/champagne/dao/DeployableSystemDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/DeployableSystemForUserMapper.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/DeployableSystemMapper.java, service/src/main/java/org/kiwiproject/champagne/model/DeployableSystem.java, service/src/main/resources/migrations.xml, service/src/test/java/org/kiwiproject/champagne/dao/BuildDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/DeployableSystemDaoTest.java, service/src/test/java/org/kiwiproject/champagne/util/TestObjects.java
Future updates will hook this into all the other models
Relates to #140
=> Add DeployableSystem model and Dao

service/src/main/java/org/kiwiproject/champagne/App.java, ui/src/layouts/MainLayout.vue, ui/src/pages/AdminSystemPage.vue, ui/src/router/routes.js, ui/src/stores/adminSystemStore.js, ui/src/stores/systemStore.js, ui/test/vitest/__tests__/pages/AdminSystemPage.spec.js, ui/test/vitest/__tests__/stores/adminSystemStore.spec.js, ui/test/vitest/__tests__/stores/systemStore.spec.js
=> Add Admin view systems page

ui/src/layouts/MainLayout.vue, ui/src/stores/systemStore.js
=> Add control to select system

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/dao/ComponentDao.java, service/src/main/java/org/kiwiproject/champagne/dao/DeployableSystemDao.java, service/src/main/java/org/kiwiproject/champagne/dao/HostDao.java, service/src/main/java/org/kiwiproject/champagne/model/DeployableSystemThreadLocal.java, service/src/main/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResource.java, service/src/main/java/org/kiwiproject/champagne/resource/HostConfigurationResource.java, service/src/main/java/org/kiwiproject/champagne/resource/filter/DeployableSystemRequestFilter.java, service/src/main/java/org/kiwiproject/champagne/util/DeployableSystems.java, service/src/test/java/org/kiwiproject/champagne/dao/ComponentDaoTest.java, service/src/test/java/org/kiwiproject/champagne/junit/jupiter/DeployableSystemExtension.java, service/src/test/java/org/kiwiproject/champagne/resource/DeploymentEnvironmentResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/HostConfigurationResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/filter/DeployableSystemRequestFilterTest.java, service/src/test/java/org/kiwiproject/champagne/resource/filter/DeployableSystemResponseFilterTest.java, service/src/test/java/org/kiwiproject/champagne/util/DeployableSystemsTest.java, service/src/test/java/org/kiwiproject/champagne/util/TestObjects.java, ui/src/components/Cards/CardTable.vue, ui/src/components/SideBar/SideBar.vue, ui/src/router/index.js, ui/src/views/Observability/ComponentView.vue, ui/src/views/Observability/HostConfigView.vue
* Component management is on its own page now
* Components per host is still viewable on the host page
* Add ability to update host and component
* Add auth to ensure calls that require admin are protected
=> Split Host and Component management

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/dao/BuildDao.java, service/src/main/java/org/kiwiproject/champagne/resource/MetricsResource.java, service/src/test/java/org/kiwiproject/champagne/dao/BuildDaoTest.java, service/src/test/java/org/kiwiproject/champagne/resource/MetricsResourceTest.java, ui/src/stores/stats.js
Update UI to use new endpoint for build stats
=> Add endpoint to retrieve build stats

service/src/main/java/org/kiwiproject/champagne/App.java, service/src/main/java/org/kiwiproject/champagne/dao/UserDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/UserInSystemMapper.java, service/src/main/java/org/kiwiproject/champagne/model/User.java, service/src/main/java/org/kiwiproject/champagne/model/UserInSystem.java, service/src/main/java/org/kiwiproject/champagne/resource/UserResource.java, service/src/test/java/org/kiwiproject/champagne/dao/UserDaoTest.java, service/src/test/java/org/kiwiproject/champagne/resource/UserResourceTest.java, service/src/test/java/org/kiwiproject/champagne/resource/apps/TestUserApp.java, ui/src/components/Dropdowns/TableActionsDropdown.vue, ui/src/components/SideBar/SideBar.vue, ui/src/router/index.js, ui/src/views/ChampagneAdmin/UsersView.vue, ui/src/views/SystemAdmin/SystemUsersView.vue
* Users in a system to include editing system admin flag and remove from system
* Global user viewing to include adding users, editing users, removing users, and adding users to a system.
* New tests
=> Add User pages

service/src/main/java/org/kiwiproject/champagne/dao/AuditRecordDao.java, service/src/main/java/org/kiwiproject/champagne/resource/AuditRecordResource.java, service/src/test/java/org/kiwiproject/champagne/dao/AuditRecordDaoTest.java, service/src/test/java/org/kiwiproject/champagne/resource/AuditRecordResourceTest.java, ui/src/components/Audits/AuditViewer.vue, ui/src/components/SideBar/SideBar.vue, ui/src/router/index.js, ui/src/views/ChampagneAdmin/AuditsView.vue, ui/src/views/SystemAdmin/SystemAuditsView.vue
* Audit view for Deployable System admin
* Audit view for Champagne admin
* Add tests
=> Add Audit viewing pages

service/src/main/java/org/kiwiproject/champagne/dao/DeploymentDao.java, service/src/main/java/org/kiwiproject/champagne/dao/DeploymentExecutionDao.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/DeploymentExecutionMapper.java, service/src/main/java/org/kiwiproject/champagne/dao/mappers/DeploymentMapper.java, service/src/main/java/org/kiwiproject/champagne/model/Deployment.java, service/src/main/java/org/kiwiproject/champagne/model/DeploymentExecution.java, service/src/main/resources/migrations.xml, service/src/test/java/org/kiwiproject/champagne/dao/DeploymentDaoTest.java, service/src/test/java/org/kiwiproject/champagne/dao/DeploymentExecutionDaoTest.java, service/src/test/java/org/kiwiproject/champagne/util/TestObjects.java
Add initial DAOs for each.
Closes #128 and #129
=> Add models for Deployments and Deployment Executions
